on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master

      - name: Set VERSION variable from tag or commit
        run: |
          set -e
          git fetch --tags
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null) || true
          if [[ -n "$TAG" && "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            VERSION=$TAG
          else
            COMMIT_HASH=$(git rev-parse --short HEAD)
            VERSION="0.0.0-$COMMIT_HASH"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Build
        run: dotnet build --configuration Release /p:Version=${{ env.VERSION }}
      - name: Test
        id: test
        run: dotnet test --configuration Release /p:Version=${{ env.VERSION }} --no-build
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ env.VERSION }} --no-build --output ./artifacts
        if: steps.test.outcome == 'success'
      - name: Publish
        run: dotnet nuget push ./artifacts/*.nupkg --source https://nuget.pkg.github.com/SoftsLights/index.json --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GIF_HARNESS_GITHUB_TOKEN_CICD }}
        if: steps.test.outcome == 'success'
  